language: python

python: 
        - 3.6

before_install:
        - echo "Start Installation"
        - sudo apt-get update
        - sudo apt-get install -y fitsverify 


install:
        - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda info -a
        - conda env create -n test-environment python=$TRAVIS_PYTHON_VERSION -f environment.yml
        - source activate test-environment

script:
        - for i in $(ls -d */); do
            cd $i;
            py.test || exit 1;
            if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then
            jupyter nbconvert $i --stdout --to python --PythonExporter.exclude_markdown=True| flake8 - --max-line-length 120 --ignore=F841,W391 || exit -1; 
            fi;
            cd ..;
            done


after_success:
        - echo "Build success"
 
