language: python

python: 
        - 3.6
        - 3.7

before_install:
        - echo "Start Installation"
        - sudo apt-get update
        - sudo pip3 install --upgrade pip 


install:
        - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda info -a
        - conda env create -n test-environment python=$TRAVIS_PYTHON_VERSION -f requirement.yml
        - source activate test-environment 
        - pip install appmode
        - jupyter nbextension enable --py --sys-prefix appmode
        - jupyter serverextension enbale --py --sys-prefix apppmode
        - pip install git+https://github.com/glue-viz/glue-jupyter.git
        - pip install cadcutils
        - pip install cadctap
        - pip install ipywidgets
        - pip install ipyvuetify

script:
        - py.test

after_success:
        - echo "Build success"
