channels:
    - conda-forge    

dependencies:              
    - appmode
    - pandas
    - numpy
    - IPython
    - astropy
    - python
    - pip3
    - pip3:
            - pyvo
            - cadcutils
            - cadctap
            - git+https://github.com/glue-viz/glue-jupyter.git
            - ipyvuetify
            - astroquery
            - drawSvg
            - flake8
